### ISSUE TITLE
Instructions for modding

### ISSUE THREAD

**Issue by CoolModder** [zpchavez/Bartizan#52]
Dear @zpchavez,
The instructions for making custom mods are very unclear, and have no information on how to make a mod.dll.
Can you please help explain how to do this?
From,
CoolModder

**Comment by zpchavez** [comment]
1. Check out the master branch if you're on mac, windows-build branch if you're on windows. If you already did so, check if you've got the latest since I fixed some things recently. I'll assume you're on windows for the rest of these steps.
1. Follow the [instructions](https://github.com/zpchavez/Bartizan#how-to-work-on-your-own-mods) from the README, putting everything in `bin` that belongs there.
2. Open the Bartizan.sln file in Visual Studio
3.  Select the version of TF you're working on by right clicking Solution 'Bartizan' and select Properties. Then select Configuration Properties and under the Mod project select either 8-player, 4-player, or 4-player-itch.
4. Build the Patcher by right clicking Patcher and selecting "build". If it succeeded the output will say "Build succeeded" at the end.
5. Under Mod right click References and select Add Reference. Under Browse select the BaseTowerfall.exe for the version you want to patch.
6. Then try building the Mod project like you did with Patcher a couple steps ago. If you see "Build Succeeded" then that means you'll have a patched `TowerFall-4-player-patched.exe` in `/bin` as well as atlas files in e.g. `<BartizanPath>/bin/builds/4-player/`.

Ideally that should all work. In reality you'll likely hit some snags. If you get errors when building post them here and I'll see if I can help.

**Comment by zpchavez** [comment]
Actually I think those atlas files end up some place different currently. Looks like `bin\Content\Atlas\modAtlas-4-player.png`.

**Comment by CoolModder** [comment]
Thank you!

**Comment by CoolModder** [comment]
I think I broke something... Why did I need this much things...The MonoModdedTowerfall.exe does not work due to an error in the comment below. On top of that, Monomod kept crashing until I put all the dlls there and the wizard won't run from the folder, crashing with this error: `Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Mono.Cecil, Version=0.9.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Wizard.Program.Main() in D:\logan\Documents\Bartizan-master\Wizard\Program.cs:line 72` The zip file is a copy of the broken executable. I am a beginner.
![image](https://user-images.githubusercontent.com/132532001/236352385-f526ec62-4648-4704-aff1-9cb382197924.png)

[MONOMODDED_TowerFall.zip](https://github.com/zpchavez/Bartizan/files/11402367/MONOMODDED_TowerFall.zip)

**Comment by CoolModder** [comment]
Here is the error mentioned above. Line 5 is important I think.
```
Rebuild started...
1>------ Rebuild All started: Project: Mod, Configuration: 4-player Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "FNA". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "BaseTowerFall, Version=1.0.0.0, Culture=neutral, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB1337: Mod Channel Reimplemented, look at file Dantinou.Dll for more info, this is a warning for Zach.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Microsoft.Xna.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Microsoft.Xna.Framework.Game, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Microsoft.Xna.Framework.Graphics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Microsoft.Xna.Framework.Xact, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Patcher, Version=1.0.8522.36000, Culture=neutral, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>D:\n\Documents\Bartizan-master\Mod\Classes\Patched\MapScene.cs(13,25,13,36): warning CS0414: The field 'patch_MapScene.initialLoad' is assigned but its value is never used
1>  Mod -> D:\n\Documents\Bartizan-master\bin\Mod.dll
1>  MonoMod 22.5.1.1
1>  [MonoMod] Reading input file into module.
1>  [MonoMod] [Main] Scanning for mods in directory.
1>  [MonoMod] [ReadMod] Loading mod dir: D:\l\Documents\Bartizan-master\bin
1>  [MonoMod] [ReadMod] Loading mod: D:\l---\Documents\Bartizan-master\bin\TowerFall.Mod.mm.dll
1>  [MonoMod] [Main] mm.AutoPatch();
1>  [MonoMod] [AutoPatch] Parsing rules in loaded mods
1>  [MonoMod] [AutoPatch] PrePatch pass
1>  [MonoMod] [AutoPatch] Patch pass
1>  [MonoMod] [AutoPatch] PatchRefs pass
1>  [MonoMod] [PostProcessor] PostProcessor pass #1
1>  [MonoMod] [Write] Writing modded module into output file.
1>  System.Runtime.InteropServices.MarshalDirectiveException: Not implemented.
1>    at (wrapper managed-to-native) Mono.Cecil.Pdb.ISymUnmanagedWriter2.GetDebugInfo(intptr,Mono.Cecil.Cil.ImageDebugDirectory&,int,int&,byte[])
1>    at (wrapper cominterop) Mono.Cecil.Pdb.ISymUnmanagedWriter2.GetDebugInfo(Mono.Cecil.Cil.ImageDebugDirectory&,int,int&,byte[])
1>    at (wrapper cominterop-invoke) Mono.Cecil.Pdb.ISymUnmanagedWriter2.GetDebugInfo(Mono.Cecil.Cil.ImageDebugDirectory&,int,int&,byte[])
1>    at Mono.Cecil.Pdb.SymWriter.GetDebugInfo (Mono.Cecil.Cil.ImageDebugDirectory& idd) [0x00000] in <f87ec0d640864d33929c3395b6a237d8>:0 
1>    at Mono.Cecil.Pdb.NativePdbWriter.GetDebugHeader () [0x00000] in <f87ec0d640864d33929c3395b6a237d8>:0 
1>    at Mono.Cecil.PE.ImageWriter.GetDebugHeader () [0x0000f] in <8d9dd476eed0422b8775a719e22dbc54>:0 
1>    at Mono.Cecil.PE.ImageWriter..ctor (Mono.Cecil.ModuleDefinition module, System.String runtime_version, Mono.Cecil.MetadataBuilder metadata, Mono.Disposable`1[T] stream, System.Boolean metadataOnly) [0x0007e] in <8d9dd476eed0422b8775a719e22dbc54>:0 
1>    at Mono.Cecil.PE.ImageWriter.CreateWriter (Mono.Cecil.ModuleDefinition module, Mono.Cecil.MetadataBuilder metadata, Mono.Disposable`1[T] stream) [0x00000] in <8d9dd476eed0422b8775a719e22dbc54>:0 
1>    at Mono.Cecil.ModuleWriter.Write (Mono.Cecil.ModuleDefinition module, Mono.Disposable`1[T] stream, Mono.Cecil.WriterParameters parameters) [0x00112] in <8d9dd476eed0422b8775a719e22dbc54>:0 
1>    at Mono.Cecil.ModuleWriter.WriteModule (Mono.Cecil.ModuleDefinition module, Mono.Disposable`1[T] stream, Mono.Cecil.WriterParameters parameters) [0x00002] in <8d9dd476eed0422b8775a719e22dbc54>:0 
1>    at Mono.Cecil.ModuleDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters) [0x00017] in <8d9dd476eed0422b8775a719e22dbc54>:0 
1>    at MonoMod.MonoModder.Write (System.IO.Stream output, System.String outputPath) [0x0005f] in <859b6ac61c8b497787f027d864042d21>:0 
1>    at MonoMod.Program.Main (System.String[] args) [0x0026e] in <859b6ac61c8b497787f027d864042d21>:0 
1>EXEC : warning : The runtime version supported by this application is unavailable.
1>  Using default runtime: v4.0.30319
1>D:\---\Documents\Bartizan-master\Mod\Mod.csproj(294,5): error MSB3073: The command "mono ..\bin\MonoMod.exe TowerFall.exe" exited with code -1.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

```

**Comment by Terria-K** [comment]
By the looks of it, Patcher's Mono Cecil dependencies are outdated and must need to update to the newer version. And your MonoMod doesn't seem to work in runtime lower than 4.0 I guess? You probably have to migrate from mono to dotnet and change how the project file (.csproj) looks.

**Comment by CoolModder** [comment]
> By the looks of it, Patcher's Mono Cecil dependencies are outdated and must need to update to the newer version. And your MonoMod doesn't seem to work in runtime lower than 4.0 I guess? You probably have to migrate from mono to dotnet and change how the project file (.csproj) looks.

How do I do that?

**Comment by Terria-K** [comment]
> > By the looks of it, Patcher's Mono Cecil dependencies are outdated and must need to update to the newer version. And your MonoMod doesn't seem to work in runtime lower than 4.0 I guess? You probably have to migrate from mono to dotnet and change how the project file (.csproj) looks.
> 
> How do I do that?

For Mono cecil, download the latest version through nuget or with dlls from their github repository, and/or also compile the Patcher project with the reference of the newest Mono cecil.. For migrating from mono to dotnet, download the latest .NET SDK from Microsoft .NET website. If you don't want to upgrade and update the project file, then try changing the TargetFrameworkVersion of the Mod from 4.0 to 4.5.2 or 4.7.2 depends on what you have.

**Comment by CoolModder** [comment]
> > > By the looks of it, Patcher's Mono Cecil dependencies are outdated and must need to update to the newer version. And your MonoMod doesn't seem to work in runtime lower than 4.0 I guess? You probably have to migrate from mono to dotnet and change how the project file (.csproj) looks.
> > 
> > 
> > How do I do that?
> 
> For Mono cecil, download the latest version through nuget or with dlls from their github repository, and/or also compile the Patcher project with the reference of the newest Mono cecil.. For migrating from mono to dotnet, download the latest .NET SDK from Microsoft .NET website. If you don't want to upgrade and update the project file, then try changing the TargetFrameworkVersion of the Mod from 4.0 to 4.5.2 or 4.7.2 depends on what you have.

Fixed that, patcher had a old version in packages.config. How do I fix this:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1729	'GenericParameter' does not contain a constructor that takes 3 arguments	Patcher	
D:\---\Documents\Bartizan-master\Patcher\Program.cs	131	Active
`

**Comment by Terria-K** [comment]
> > > > By the looks of it, Patcher's Mono Cecil dependencies are outdated and must need to update to the newer version. And your MonoMod doesn't seem to work in runtime lower than 4.0 I guess? You probably have to migrate from mono to dotnet and change how the project file (.csproj) looks.
> > > 
> > > 
> > > How do I do that?
> > 
> > For Mono cecil, download the latest version through nuget or with dlls from their github repository, and/or also compile the Patcher project with the reference of the newest Mono cecil.. For migrating from mono to dotnet, download the latest .NET SDK from Microsoft .NET website. If you don't want to upgrade and update the project file, then try changing the TargetFrameworkVersion of the Mod from 4.0 to 4.5.2 or 4.7.2 depends on what you have.
> 
> Fixed that, patcher had a old version in packages.config. How do I fix this:
> `Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS1729	'GenericParameter' does not contain a constructor that takes 3 arguments	Patcher	
> D:\---\Documents\Bartizan-master\Patcher\Program.cs	131	Active
> `

It looks like there may be breaking changes in the function in line 131. Look at the function and see what it needs. You might just change the parameter a little.

**Comment by CoolModder** [comment]
Was looking at the 0.10 version github repo, and saw this:
`public sealed class GenericParameter : TypeReference, ICustomAttributeProvider{`
At: https://github.com/jbevain/cecil/blob/release/0.10/Mono.Cecil/GenericParameter.cs
And this from Bartizan Patcher(Line 131), `GenericParameter(modParam.Position, GenericParameterType.Method, modModule);`
I guess @zpchavez  forgot to put the type reference and put the provided arguments in the ICustomAttributeProvider.

**Comment by zpchavez** [comment]
Building on windows doesn't currently work in the `master` branch. That's what step 1 was about in my first reply. There's a [branch](https://github.com/zpchavez/Bartizan/tree/windows-build) called `windows-build` that I use for that.

> the wizard won't run

The wizard doesn't do anything anymore. You can ignore it.

**Comment by CoolModder** [comment]
> Building on windows doesn't currently work in the `master` branch. That's what step 1 was about in my first reply. There's a [branch](https://github.com/zpchavez/Bartizan/tree/windows-build) called `windows-build` that I use for that.
> 
> > the wizard won't run
> 
> The wizard doesn't do anything anymore. You can ignore it.

The windows branch was what I started out using. It didn't work. I guess I'll try again...

**Comment by CoolModder** [comment]
I used the windows branch. The same error as before happened with building the mod project, resulting in a broken exe.
The wizard worked after I built the mod.dll. However, I broke the variants with my additions.

**Comment by zpchavez** [comment]
Looks like I may have broke the nuget packages when I migrated to PackageReference format. Just need to add these packages to the Mod project (I'm guessing):

https://github.com/zpchavez/Bartizan/blob/57a13e3793d40400039a21c03b2e47bf40f3ed93/Mod/packages.config
