### ISSUE TITLE
The Patching Process

### ISSUE THREAD

**Issue by CoolModder** [zpchavez/Bartizan#53]
This is an incredibly hard framework to use. The custom mod section needs to be updated to be more clear.
However, I got it to patch after trying hard (using Windows-build.)
It created a vanilla Towerfall with the MonoMod piece of MonoMod.WasHere. 
Here is a copy of the Mod.dll
[ModDll.zip](https://github.com/zpchavez/Bartizan/files/11468588/ModDll.zip)
Also, some scripts attempt to modify protected classes and tries to override some nonexistent classes.
Finally, thanks for putting in the effort to keep the modding framework alive.

**Comment by zpchavez** [comment]
I think I broke packages on `windows-build` which is at least partly to blame. It's probably best to wait until I can get around to fixing whatever I broke, but I can't say when that will be
